(add-to-list 'load-path "~/.emacs.d")
(add-to-list 'load-path "~/.emacs.d/vendor")
(add-to-list 'load-path "~/.emacs.d/vendor/pony-mode/src")
(add-to-list 'load-path "/usr/local/lib/erlang/lib/tools-2.6.8/emacs/")

(load "kpachnis/defuns")

(vendor 'magit)
(vendor 'markdown-mode)
(vendor 'pony-mode)
(vendor 'jinja2-mode)
(vendor 'ruby-mode)
(vendor 'rails)
(vendor 'rhtml-mode)
(vendor 'haml-mode)
(vendor 'yaml-mode)
(vendor 'less-mode)
(vendor 'scss-mode)
(vendor 'slime)
(vendor 'python-mode)
(vendor 'puppet-mode)
(vendor 'po-mode)
(vendor 'autopair)

(load "kpachnis/custom")
(load "kpachnis/global")
(load "kpachnis/bindings")
(load "kpachnis/modes")
(load "kpachnis/theme")
(load "kpachnis/ui")
